import { useEffect, useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { apiUrl, parseJsonResponse } from "@/lib/api";
import { Play, Square, Sparkles, Sunrise, CheckCircle2, FileText, Volume2, Languages } from "lucide-react";

interface DailyZenResult {
  id?: string;
  greeting: string;
  weatherLine: string;
  recoveryLine: string;
  motivationLine: string;
  todayGoal: string;
  briefingText: string;
  actionChecklist: string[];
  source?: string;
  createdAt?: string;
  autoGenerated?: boolean;
}

interface DailyZenBriefingProps {
  userId: string | null;
  userName: string;
}

const DailyZenBriefing = ({ userId, userName }: DailyZenBriefingProps) => {
  const [loading, setLoading] = useState(false);
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [deliveryMode, setDeliveryMode] = useState<"text" | "voice" | "both">("both");
  const [city, setCity] = useState("");
  const [weatherNote, setWeatherNote] = useState("");
  const [sleepHours, setSleepHours] = useState("");
  const [todayGoal, setTodayGoal] = useState("");
  const [moodCountLast7Days, setMoodCountLast7Days] = useState("");
  const [streakDays, setStreakDays] = useState("");
  const [savedMessage, setSavedMessage] = useState("");
  const [error, setError] = useState("");
  const [result, setResult] = useState<DailyZenResult | null>(null);
  const [history, setHistory] = useState<DailyZenResult[]>([]);

  const draftKey = userId ? `dailyZenDraft_${userId}` : "dailyZenDraft_guest";

  const stopVoice = () => {
    if (!("speechSynthesis" in window)) return;
    window.speechSynthesis.cancel();
    setIsSpeaking(false);
  };

  const speakText = (text: string) => {
    if (!("speechSynthesis" in window) || !text) return;

    try {
      window.speechSynthesis.cancel();
      const utterance = new SpeechSynthesisUtterance(text);
      utterance.lang = "en-IN";
      utterance.rate = 0.95;
      utterance.pitch = 1;
      utterance.onend = () => setIsSpeaking(false);
      utterance.onerror = () => setIsSpeaking(false);
      setIsSpeaking(true);
      window.speechSynthesis.speak(utterance);
    } catch {
      setIsSpeaking(false);
    }
  };

  const loadHistory = async () => {
    try {
      const token = localStorage.getItem("jwtToken");
      if (!token) return;

      const response = await fetch(apiUrl("/api/daily-zen/history"), {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });

      if (!response.ok) return;
      const data = await parseJsonResponse(response, "Unable to load daily zen history");
      setHistory(Array.isArray(data) ? data : []);
    } catch {
      // Ignore history errors
    }
  };

  useEffect(() => {
    try {
      const raw = localStorage.getItem(draftKey);
      if (raw) {
        const draft = JSON.parse(raw);
        setCity(String(draft?.city || ""));
        setWeatherNote(String(draft?.weatherNote || ""));
        setSleepHours(String(draft?.sleepHours || ""));
        setTodayGoal(String(draft?.todayGoal || ""));
        setMoodCountLast7Days(String(draft?.moodCountLast7Days || ""));
        setStreakDays(String(draft?.streakDays || ""));
      }
    } catch {
      // Ignore invalid draft JSON
    }

    loadHistory();
    return () => stopVoice();
  }, [draftKey]);

  const shouldSpeak = (mode: "text" | "voice" | "both") => mode === "voice" || mode === "both";

  const modeLabel = deliveryMode === "text"
    ? "Text Briefing"
    : deliveryMode === "voice"
      ? "Voice Briefing"
      : "Text + Voice";

  const toOptionalNumber = (value: string) => {
    const trimmed = String(value || "").trim();
    if (!trimmed) return undefined;
    const parsed = Number(trimmed);
    return Number.isFinite(parsed) ? parsed : undefined;
  };

  const getEffectiveInputs = () => {
    let draft: any = {};
    try {
      draft = JSON.parse(localStorage.getItem(draftKey) || "{}");
    } catch {
      draft = {};
    }

    const pick = (current: string, saved: any) => {
      const c = String(current || "").trim();
      if (c) return c;
      return String(saved || "").trim();
    };

    const cityValue = pick(city, draft?.city);
    const weatherValue = pick(weatherNote, draft?.weatherNote);
    const goalValue = pick(todayGoal, draft?.todayGoal);
    const sleepValue = pick(sleepHours, draft?.sleepHours);
    const moodCountValue = pick(moodCountLast7Days, draft?.moodCountLast7Days);
    const streakValue = pick(streakDays, draft?.streakDays);

    return {
      city: cityValue,
      weatherNote: weatherValue,
      todayGoal: goalValue,
      sleepHours: toOptionalNumber(sleepValue),
      moodCountLast7Days: toOptionalNumber(moodCountValue),
      streakDays: toOptionalNumber(streakValue),
    };
  };

  const saveTypedInputs = () => {
    const draft = {
      city: city.trim(),
      weatherNote: weatherNote.trim(),
      sleepHours: sleepHours.trim(),
      todayGoal: todayGoal.trim(),
      moodCountLast7Days: moodCountLast7Days.trim(),
      streakDays: streakDays.trim(),
      savedAt: new Date().toISOString(),
    };

    localStorage.setItem(draftKey, JSON.stringify(draft));
    setSavedMessage("Inputs saved successfully.");
    setTimeout(() => setSavedMessage(""), 2500);
  };

  const generateBriefing = async () => {
    setError("");
    setLoading(true);

    try {
      const token = localStorage.getItem("jwtToken");
      if (!token) {
        throw new Error("Please login again to continue.");
      }

      const effective = getEffectiveInputs();

      // Send minimal payload - backend auto-fetches everything
      const response = await fetch(apiUrl("/api/daily-zen/generate"), {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({
          userName: userName || "User",
          city: effective.city,
          weatherNote: effective.weatherNote,
          todayGoal: effective.todayGoal,
          sleepHours: effective.sleepHours,
          moodCountLast7Days: effective.moodCountLast7Days,
          streakDays: effective.streakDays,
          // Backend auto-generates any field left empty
        }),
      });

      const data = await parseJsonResponse(response, "Unable to parse Daily Zen response");
      if (!response.ok) {
        throw new Error(data?.message || "Failed to generate Daily Zen briefing");
      }

      setResult(data);
      setHistory((prev) => [data, ...prev].slice(0, 20));
      
      if (shouldSpeak(deliveryMode)) {
        // Auto-play only when voice is enabled
        setTimeout(() => {
          speakText(data?.briefingText || "Good morning. Have a calm and focused day.");
        }, 300);
      }
    } catch (err: any) {
      setError(err?.message || "Daily Zen generation failed");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-5">
      <Card className="card-elevated border-primary/20">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-2xl font-bold text-gradient-primary">
            <Sunrise className="h-6 w-6 text-primary" />
            The Daily Zen
          </CardTitle>
          <CardDescription>
            ✨ AI-powered personalized morning briefing. Everything is auto-generated based on your wellness patterns and data.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-5">
          <div className="grid gap-3 md:grid-cols-2">
            <div className="space-y-2">
              <label className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                City (optional)
              </label>
              <input
                value={city}
                onChange={(e) => setCity(e.target.value)}
                placeholder="Ahmedabad"
                className="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm"
              />
            </div>

            <div className="space-y-2">
              <label className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                Weather note (optional)
              </label>
              <input
                value={weatherNote}
                onChange={(e) => setWeatherNote(e.target.value)}
                placeholder="cool and breezy"
                className="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm"
              />
            </div>

            <div className="space-y-2">
              <label className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                Sleep hours (optional)
              </label>
              <input
                value={sleepHours}
                onChange={(e) => setSleepHours(e.target.value)}
                placeholder="7.5"
                type="number"
                min={0}
                step="0.5"
                className="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm"
              />
            </div>

            <div className="space-y-2">
              <label className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                Today's goal (optional)
              </label>
              <input
                value={todayGoal}
                onChange={(e) => setTodayGoal(e.target.value)}
                placeholder="10 min mindful walk"
                className="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm"
              />
            </div>

            <div className="space-y-2">
              <label className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                Mood check-ins (7 days)
              </label>
              <input
                value={moodCountLast7Days}
                onChange={(e) => setMoodCountLast7Days(e.target.value)}
                placeholder="5"
                type="number"
                min={0}
                className="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm"
              />
            </div>

            <div className="space-y-2">
              <label className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                Streak days (optional)
              </label>
              <input
                value={streakDays}
                onChange={(e) => setStreakDays(e.target.value)}
                placeholder="3"
                type="number"
                min={0}
                className="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm"
              />
            </div>
          </div>

          <div className="rounded-lg border border-border/60 bg-muted/30 px-3 py-2 text-xs text-muted-foreground">
            Sabhi fields likhne ka option available hai. Jo blank chhodoge, wo AI auto-generate karega.
          </div>

          <div className="flex flex-wrap gap-2">
            <Button type="button" variant="outline" onClick={saveTypedInputs}>
              Save Typed Inputs
            </Button>
            {savedMessage ? <p className="text-xs text-green-700 self-center">{savedMessage}</p> : null}
          </div>

          <div className="grid gap-2 sm:grid-cols-3">
            <Button
              type="button"
              variant={deliveryMode === "text" ? "default" : "outline"}
              onClick={() => setDeliveryMode("text")}
              className="justify-start"
            >
              <FileText className="mr-2 h-4 w-4" />
              Text Only
            </Button>
            <Button
              type="button"
              variant={deliveryMode === "voice" ? "default" : "outline"}
              onClick={() => setDeliveryMode("voice")}
              className="justify-start"
            >
              <Volume2 className="mr-2 h-4 w-4" />
              Voice Only
            </Button>
            <Button
              type="button"
              variant={deliveryMode === "both" ? "default" : "outline"}
              onClick={() => setDeliveryMode("both")}
              className="justify-start"
            >
              <Languages className="mr-2 h-4 w-4" />
              Text + Voice
            </Button>
          </div>

          <div className="rounded-lg border border-border/60 bg-muted/30 px-3 py-2 text-xs text-muted-foreground">
            Selected mode: <span className="font-semibold text-foreground">{modeLabel}</span>
          </div>

          {/* Auto-Generate Button */}
          <div className="flex gap-3">
            <Button
              onClick={generateBriefing}
              disabled={loading}
              className="flex-1 h-12 bg-gradient-to-r from-primary to-accent text-white font-semibold hover:shadow-lg transition"
            >
              {loading ? (
                <>
                  <span className="animate-spin mr-2">⏳</span>
                  Generating your unique briefing...
                </>
              ) : (
                <>
                  <Sparkles className="mr-2 h-4 w-4" />
                  Generate My Daily Zen
                </>
              )}
            </Button>
          </div>

          {/* Error Display */}
          {error && (
            <div className="rounded-lg bg-red-50 border border-red-200 p-3">
              <p className="text-sm text-red-700">{error}</p>
            </div>
          )}

          {/* Result Display */}
          {result && (
            <div className="space-y-4">
              <Card className="bg-gradient-to-br from-primary/5 to-accent/5 border-primary/30">
                <CardContent className="pt-6">
                  {/* Greeting + Weather + Recovery */}
                  <div className="space-y-3 mb-5">
                    <p className="text-xl font-bold text-gradient-primary">
                      {result.greeting || "Good morning!"}
                    </p>
                    <p className="text-sm text-muted-foreground leading-relaxed">
                      {result.weatherLine || ""}
                    </p>
                    <p className="text-sm text-muted-foreground leading-relaxed">
                      {result.recoveryLine || ""}
                    </p>
                    <p className="text-sm font-semibold text-foreground italic">
                      {result.motivationLine || ""}
                    </p>
                  </div>

                  {/* Full Briefing Text */}
                  <div className="rounded-lg bg-card/60 p-4 border border-border/50 mb-4">
                    <p className="text-sm leading-relaxed text-foreground">
                      {result.briefingText || ""}
                    </p>
                  </div>

                  {/* Voice Controls */}
                  <div className="flex gap-2 mb-5">
                    <Button
                      onClick={() => speakText(result.briefingText || "Good morning")}
                      disabled={isSpeaking}
                      className="flex-1 bg-primary text-white hover:bg-primary/90"
                      size="sm"
                    >
                      {isSpeaking ? (
                        <>
                          <Square className="mr-2 h-4 w-4 fill-current" />
                          Stop Voice
                        </>
                      ) : (
                        <>
                          <Play className="mr-2 h-4 w-4" />
                          Play Voice Briefing
                        </>
                      )}
                    </Button>
                  </div>

                  {/* Action Checklist */}
                  {result.actionChecklist && result.actionChecklist.length > 0 && (
                    <div className="border-t border-border/30 pt-4">
                      <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-3">
                        🎯 Today's Action Checklist:
                      </p>
                      <div className="space-y-2">
                        {result.actionChecklist.map((action, idx) => (
                          <div key={idx} className="flex items-start gap-3">
                            <CheckCircle2 className="h-4 w-4 mt-0.5 text-primary flex-shrink-0" />
                            <span className="text-sm text-foreground">{action}</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* Metadata */}
                  <div className="border-t border-border/30 mt-4 pt-3">
                    <p className="text-xs text-muted-foreground">
                      ⏱️ Generated: {result.createdAt ? new Date(result.createdAt).toLocaleString("en-IN") : "just now"}
                      {result.source && <span> • {result.autoGenerated ? "🤖 Auto-generated" : `Source: ${result.source}`}</span>}
                    </p>
                  </div>
                </CardContent>
              </Card>
            </div>
          )}

          {/* History Section */}
          {history.length > 0 && (
            <div className="border-t pt-5">
              <p className="text-sm font-semibold text-foreground mb-3">📚 Your Recent Briefings:</p>
              <div className="space-y-2 max-h-64 overflow-y-auto">
                {history.map((item, idx) => (
                  <div
                    key={idx}
                    className="rounded-lg bg-card/50 border border-border/30 p-3 cursor-pointer hover:bg-card/80 transition"
                    onClick={() => {
                      setResult(item);
                      if (shouldSpeak(deliveryMode)) {
                        speakText(item.briefingText || "");
                      }
                    }}
                  >
                    <p className="text-xs font-semibold text-primary">
                      {item.greeting || "Briefing"}
                    </p>
                    <p className="text-xs text-muted-foreground truncate">
                      {item.briefingText || ""}
                    </p>
                    <p className="text-xs text-muted-foreground/60 mt-1">
                      {item.createdAt ? new Date(item.createdAt).toLocaleString("en-IN") : ""}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
};

export default DailyZenBriefing;
